config/routes.rb
Rails.application.routes.draw do
  
  root "top#index"

  devise_for :users, controllers: {
    registrations: "users/registrations",
  }

  resources :users, only: [:show] do
    member do
      get 'liked'
    end
  end
  
  resources :groups do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
    resources :wents, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :scores, only: [:index]

  resources :areas do
    collection do
      get 'tokyo'
      get 'kanagawa'
      get 'chiba'
      get 'ibaraki'
      get 'saitama'
      get 'tochigi'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :group, optional: true
  belongs_to :user

  validates :title, presence: true, length: { maximum: 20 }
  validates :text, presence: true, length: { maximum: 140 }
  validates :visit_date, presence: true
  validates :rate, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  # belongs_to :user
  has_many :saves
  has_many :images
  has_many :comments
  has_many :wents, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :group, optional: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true, length: { maximum: 10 }
  validates :email, uniqueness: true
  # validates :password,
  # format: {
  #   with: /\A[a-zA-Z0-9]+\z/
  # }

  has_many :likes, dependent: :destroy
  has_many :like_groups, through: :likes, source: :group
  has_many :wents, dependent: :destroy
  has_many :went_groups, through: :wents, source: :group
  has_many :comments

  mount_uploader :image, ImageUploader
end

app/models/went.rb
class Went < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController

  before_action :set_all

  def tokyo
    @groups = Group.where(area: "東京")
  end

  def kanagawa
    @groups = Group.where(area: "神奈川")
  end

  def chiba
    @groups = Group.where(area: "千葉")
  end

  def ibaraki
    @groups = Group.where(area: "茨城")
  end

  def saitama
    @groups = Group.where(area: "埼玉")
  end

  def tochigi
    @groups = Group.where(area: "栃木")
  end

  private

  def set_all
    @all_comments = Comment.all
    @all_groups = Group.all
    @q = Group.ransack(params[:q])
  end

  def search_params
    params.require(:q).permit(:area, :text)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  before_action :set_all
  
  def index
    @groups = Group.includes(:images).order('created_at DESC')
  end

  def new
    @group = Group.new
    5.times{@group.images.build}
  end

  def show
    @group = Group.find(params[:id])
    @comment = Comment.new
    @comments = @group.comments.includes(:user)
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
    5.times{@group.images.build}
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  def search
    @search_product = Group.ransack(params[:q]) 
    @groups = @search_product.result
    # @input = Group.search(params[:keyword]) 
    # respond_to do |format|
    #   format.html
    #   format.json
    # end
  end

  private
  def group_params
    params.require(:group).permit(:name, :catchphrase, :title, :text, :area, images_attributes: [:image])
  end

  def set_all
    @all_comments = Comment.all
    @all_groups = Group.all
    @q = Group.ransack(params[:q])
  end

  def search_params
    params.require(:q).permit(:area, :text)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_group

  def create
    @like = Like.create(user_id: current_user.id, group_id: params[:group_id])
    @likes = Like.where(group_id: params[:group_id])
    @group.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, group_id: params[:group_id])
    like.destroy
    @likes = Like.where(group_id: params[:group_id])
    @group.reload
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :set_all

  def index
    @groups = Group.all.sort {|a,b| b.comments.average(:rate).to_f <=> a.comments.average(:rate).to_f}.first(5)
    @q = Group.ransack(params[:q])
  end

  private

  def set_all
    @all_comments = Comment.all
    @all_groups = Group.all
  end

  def search_params
    params.require(:q).permit(:area, :text)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_all
  
  def show
    @user = current_user
    @groups = current_user.went_groups
  end

  def liked
    @user = current_user
    @groups = current_user.like_groups
  end

  private

  def set_all
    @all_comments = Comment.all
    @all_groups = Group.all
    @q = Group.ransack(params[:q])
  end

  def search_params
    params.require(:q).permit(:area, :text)
  end
end

app/controllers/wents_controller.rb
class WentsController < ApplicationController
  before_action :set_group

  def create
    @went = Went.create(user_id: current_user.id, group_id: params[:group_id])
    @wents = Went.where(group_id: params[:group_id])
    @group.reload
  end

  def destroy
    went = Went.find_by(user_id: current_user.id, group_id: params[:group_id])
    went.destroy
    @wents = Went.where(group_id: params[:group_id])
    @group.reload
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wents_helper.rb
module WentsHelper
end

app/views/areas/_index.html.haml
= render "common/header"

.groups-main
  .groups-main--head
    .groups-main--head__wrapper
      %h1
        - if @groups.present?
          = @groups[0].area
        の水族館
      %p
        口コミ評価が高い順にご紹介！

    = render "common/lists"
  = render "top/side-bar"

= render "top/footer"

app/views/areas/chiba.html.haml
= render "areas/index"

app/views/areas/ibaraki.html.haml
= render "areas/index"

app/views/areas/kanagawa.html.haml
= render "areas/index"

app/views/areas/saitama.html.haml
= render "areas/index"

app/views/areas/tochigi.html.haml
= render "areas/index"

app/views/areas/tokyo.html.haml
= render "areas/index"

app/views/top/_footer.html.haml
.footer
  %p Copyright (c) Suizokukanlog, Inc. All Rights Reserved.

app/views/top/_head-wrapper.html.haml
.head-wrapper
  .header
    .header__logo
      = image_tag asset_path('logo.png'), height: '22px', width: '22px', class: 'top-logo'
      = link_to "水族館ログ", root_path
    .header__right-items
      = link_to "アプリについて", "https://github.com/kobegoro0930/aquq-log", class: "header__right-items__feature"
      - if user_signed_in?
        = link_to "マイページ", "/users/#{current_user.id}", class: "header__right-items__mypage"
        = link_to "ログアウト", "/users/sign_out", method: :delete, class: "header__right-items__logout"
      - else
        = link_to "ログイン", "/users/sign_in", class: "header__right-items__login"
  .main-copy
    %h1
      水族館探しは
      %br
      水族館ログ
  .search-form
    .search-form__label
      %h2
        エリア、キーワードから探す
    .search-form__search-box
      = search_form_for(@q, url: search_groups_path, class: "in-search-form") do |f|
        .search-form__search-box__wrapper
          .search-form__search-box__wrapper__input-area
            = f.text_field :area_cont, id: 'area', class: "search-input", placeholder: 'エリア [ 例：東京 ]'
          .search-form__search-box__wrapper__input-keyword
            = f.text_field :name_or_catchphrase_or_title_or_text_cont, id: 'text', placeholder: 'キーワード [ 例：ペンギン ] '
          .search-form__search-box__wrapper__submit-btn                                                                   
            = f.submit "検  索", class: 'btn'

app/views/top/_ranking.html.haml
.ranking
  %h2
    人気の水族館

  = render "common/lists"
  
  .ranking__next
    .ranking__next__btn
      = link_to "もっと見る ＞", "/scores"
        

app/views/top/_search-by-area.html.haml
.search-by-area
  %h2
    エリアから探す
  %ul
    %li.area-box
      = image_tag asset_path('tokyo.jpg'), :size =>'69x69', class: "image-tokyo"
      %a.area-box__area{ href: '/areas/tokyo'}
        東京
        %span.area-box__value
          5館
    %li.area-box.area-box--center
      = image_tag asset_path('kanagawa.jpg'), :size =>'69x69', class: "image-tokyo"
      %a.area-box__area{ href: '/areas/kanagawa'}
        神奈川
        %span.area-box__value
          7館
    %li.area-box
      = image_tag asset_path('tiba.jpg'), :size =>'69x69', class: "image-tokyo"
      %a.area-box__area{ href: '/areas/chiba'}
        千葉
        %span.area-box__value
          2館
  %ul
    %li.area-box
      = image_tag asset_path('ibaraki.jpg'), :size =>'69x69', class: "image-tokyo"
      %a.area-box__area{ href: '/areas/ibaraki'}
        茨城
        %span.area-box__value
          3館
    %li.area-box.area-box--center
      = image_tag asset_path('saitama.jpg'), :size =>'69x69', class: "image-tokyo"
      %a.area-box__area{ href: '/areas/saitama'}
        埼玉
        %span.area-box__value
          1館
    %li.area-box
      = image_tag asset_path('totigi.jpg'), :size =>'69x69', class: "image-tokyo"
      %a.area-box__area{ href: '/areas/tochigi'}
        栃木
        %span.area-box__value
          1館

app/views/top/_side-bar.html.haml
.side-bar
  .side-bar__head
    .side-bar__head__wrapper.border
      .side-bar__head__wrapper__label      
        %i.fas.fa-map-marker-alt
        %p
          水族館
      .side-bar__head__wrapper__value
        = @all_groups.length
    .side-bar__head__wrapper
      .side-bar__head__wrapper__label
        %i.fas.fa-comment-dots
        %p
          口コミ
      .side-bar__head__wrapper__value
        = @all_comments.length
  .side-bar__login
    .side-bar__login__inner

      - if user_signed_in?
        .current_user-exist
          .side-bar__login__inner--head
            .side-bar__login__inner--head__image
              - if current_user.image?
                = image_tag current_user.image.url, class: "account-image"
              - else
                = image_tag "member_photo_noimage_thumb.png", class: "account-image"
            .side-bar__login__inner--head__name
              = current_user.name
          = link_to user_path(id: current_user.id), class: "navi-link" do
            .side-bar__login__inner__went
              %p
                = "行った水族館"
              %p
                = "#{current_user.wents.length}"
          = link_to liked_user_path(id: current_user.id), class: "navi-link" do
            .side-bar__login__inner__liked
              %p
                = "保存した水族館"
              %p
                = "#{current_user.likes.length}"
                
      - else
        %h3
          新規会員登録
        %p.side-bar__login__inner__explain
          ログインすると、コメントや画像の投稿、行った水族館を管理できるようになります。
        %p.side-bar__login__inner__friendly
          ※かんたんログインもございますので、お気軽にお試しください。
        .side-bar__login__inner__btn
          .side-bar__login__inner__btn__wrapper
            %a{ href: "/users/sign_in" }
              ログイン

  .side-bar__news
    .side-bar__news__inner

      - if user_signed_in?
        - if current_user.like_groups.present?
          .side-bar__liked-groups
            %h3
              保存した水族館
            - current_user.like_groups.last(3).each do |group|
              = link_to group_path(group), class: "detail__title" do
                .side-bar__liked-groups__group
                  .side-bar__liked-groups__group__image
                    = image_tag group.images[4].image.url, :size =>'50x50'
                  .side-bar__liked-groups__group--right
                    .side-bar__liked-groups__group--right__name
                      = group.name
                    .side-bar__liked-groups__group--right__area
                      = group.area
                    .side-bar__liked-groups__group--right__rate
                      .rate-star{id: "star_rate_#{group.name}"}

                        :javascript
                          $('#star_rate_#{group.name}').raty({
                            size: 36,
                            starOff: "#{asset_path('star-off.png')}",
                            starOn: "#{asset_path('star-on.png')}",
                            starHalf: "#{asset_path('star-half.png')}",
                            half: true,
                            readOnly: true,
                            score: "#{group.comments.average(:rate).to_f.round(2)}",
                          });

                      .rate-number
                        = group.comments.average(:rate).to_f.round(2)
            .liked-index
              = link_to "▶︎保存した水族館一覧へ", liked_user_path(id: current_user.id)
        - else
          .side-bar__liked-groups
            %h3
              保存した水族館
            %span
              = "保存した水族館はありません"

      - else
        %h3
          水族館ログからのお知らせ
        %p.side-bar__news__inner__time
          2020.09.06
        %p.side-bar__news__inner__text
          水族館ログ（関東版）を公開しました。今後の改修予定につきましては、決まり次第ご連絡いたします。
        %p.side-bar__news__inner__time
          2020.09.15
        %p.side-bar__news__inner__text
          口コミ投稿後に、水族館の詳細ページが見れなくなる不具合を修正いたしました。

app/views/top/index.html.haml
.wrapper
  = render "head-wrapper"
  .body-wrapper
    .main-wrapper
      = render "search-by-area"
      = render "ranking"
    = render "side-bar"
  = render "footer"