config/routes.rb
Rails.application.routes.draw do
  
  root "top#index"

  devise_for :users, controllers: {
    registrations: "users/registrations",
  }

  resources :users, only: [:show] do
    member do
      get 'liked'
    end
  end
  
  resources :groups do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
    resources :wents, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :scores, only: [:index]

  resources :areas do
    collection do
      get 'tokyo'
      get 'kanagawa'
      get 'chiba'
      get 'ibaraki'
      get 'saitama'
      get 'tochigi'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :group, optional: true
  belongs_to :user

  validates :title, presence: true, length: { maximum: 20 }
  validates :text, presence: true, length: { maximum: 140 }
  validates :visit_date, presence: true
  validates :rate, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  # belongs_to :user
  has_many :saves
  has_many :images
  has_many :comments
  has_many :wents, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :group, optional: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true, length: { maximum: 10 }
  validates :email, uniqueness: true
  # validates :password,
  # format: {
  #   with: /\A[a-zA-Z0-9]+\z/
  # }

  has_many :likes, dependent: :destroy
  has_many :like_groups, through: :likes, source: :group
  has_many :wents, dependent: :destroy
  has_many :went_groups, through: :wents, source: :group
  has_many :comments

  mount_uploader :image, ImageUploader
end

app/models/went.rb
class Went < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController

  before_action :set_all

  def tokyo
    @groups = Group.where(area: "東京")
  end

  def kanagawa
    @groups = Group.where(area: "神奈川")
  end

  def chiba
    @groups = Group.where(area: "千葉")
  end

  def ibaraki
    @groups = Group.where(area: "茨城")
  end

  def saitama
    @groups = Group.where(area: "埼玉")
  end

  def tochigi
    @groups = Group.where(area: "栃木")
  end

  private

  def set_all
    @all_comments = Comment.all
    @all_groups = Group.all
    @q = Group.ransack(params[:q])
  end

  def search_params
    params.require(:q).permit(:area, :text)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  before_action :set_all
  
  def index
    @groups = Group.includes(:images).order('created_at DESC')
  end

  def new
    @group = Group.new
    5.times{@group.images.build}
  end

  def show
    @group = Group.find(params[:id])
    @comment = Comment.new
    @comments = @group.comments.includes(:user)
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
    5.times{@group.images.build}
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  def search
    @search_product = Group.ransack(params[:q]) 
    @groups = @search_product.result
    # @input = Group.search(params[:keyword]) 
    # respond_to do |format|
    #   format.html
    #   format.json
    # end
  end

  private
  def group_params
    params.require(:group).permit(:name, :catchphrase, :title, :text, :area, images_attributes: [:image])
  end

  def set_all
    @all_comments = Comment.all
    @all_groups = Group.all
    @q = Group.ransack(params[:q])
  end

  def search_params
    params.require(:q).permit(:area, :text)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_group

  def create
    @like = Like.create(user_id: current_user.id, group_id: params[:group_id])
    @likes = Like.where(group_id: params[:group_id])
    @group.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, group_id: params[:group_id])
    like.destroy
    @likes = Like.where(group_id: params[:group_id])
    @group.reload
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  before_action :set_all
  
  def index
    @groups = Group.all.sort {|a,b| b.comments.average(:rate).to_f <=> a.comments.average(:rate).to_f}
    @comments = Comment.all
  end

  private

  def set_all
    @all_comments = Comment.all
    @all_groups = Group.all
    @q = Group.ransack(params[:q])
  end

  def search_params
    params.require(:q).permit(:area, :text)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :set_all

  def index
    @groups = Group.all.sort {|a,b| b.comments.average(:rate).to_f <=> a.comments.average(:rate).to_f}.first(5)
    @q = Group.ransack(params[:q])
  end

  private

  def set_all
    @all_comments = Comment.all
    @all_groups = Group.all
  end

  def search_params
    params.require(:q).permit(:area, :text)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_all
  
  def show
    @user = current_user
    @groups = current_user.went_groups
  end

  def liked
    @user = current_user
    @groups = current_user.like_groups
  end

  private

  def set_all
    @all_comments = Comment.all
    @all_groups = Group.all
    @q = Group.ransack(params[:q])
  end

  def search_params
    params.require(:q).permit(:area, :text)
  end
end

app/controllers/wents_controller.rb
class WentsController < ApplicationController
  before_action :set_group

  def create
    @went = Went.create(user_id: current_user.id, group_id: params[:group_id])
    @wents = Went.where(group_id: params[:group_id])
    @group.reload
  end

  def destroy
    went = Went.find_by(user_id: current_user.id, group_id: params[:group_id])
    went.destroy
    @wents = Went.where(group_id: params[:group_id])
    @group.reload
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wents_helper.rb
module WentsHelper
end

app/views/groups/_form.html.haml
管理者専用ページです。
= form_for(@group) do |f|
  %ul
    %li
      = f.label :水族館名
      %br/
      = f.text_field :name, class: "aquarium-name"
    %li
      = f.label :キャッチフレーズ
      %br/
      = f.text_field :catchphrase, class: "aquarium-catchphrase"
    %li
      = f.label :タイトル
      %br/
      = f.text_field :title, class: "aquarium-title"
    %li
      = f.label :テキスト
      %br/
      = f.text_area :text, class: "aquarium-text"
    %li
      = f.label :エリア
      %br/
      = f.text_field :area, class: "aquarium-area"
    %li
      = f.label :画像
      %br/
      = f.fields_for :images do |i|
        .aquarium-images
          = i.file_field :image 
    %li  
      = f.submit "Save"

app/views/groups/_group.html.haml
.group_index--block
  = group.id
  = group.name
  = link_to '編集', edit_group_path(group)
  = link_to "削除", group_path(id: group.id), method: :delete
  

app/views/groups/edit.html.haml
= render "form"

app/views/groups/index.html.haml
.group_indx
  .group_index--new
    = link_to "新規作成", new_group_path

  = render @groups

app/views/groups/new.html.haml
= render "form"

app/views/groups/search.html.haml
= render "common/header"

.groups-main
  .groups-main--head
    .groups-main--head__wrapper

      - if params[:q]['area_cont'] == "" && params[:q]['name_or_catchphrase_or_title_or_text_cont'] == ""
        %h1
          = "検索キーワードがありません。"
        %p
          = "エリア・キーワードで検索してみましょう。"

      - elsif @groups.present?
        %h1
          = "「#{params[:q]['area_cont']}」「#{params[:q]['name_or_catchphrase_or_title_or_text_cont']}」の検索結果："
          = @groups.count
          件
        %p
          = "該当の水族館をご紹介！"

      - else
        %h1
          = "「#{params[:q]['area_cont']}」「#{params[:q]['name_or_catchphrase_or_title_or_text_cont']}」で一致する水族館はありませんでした"
        %p
          = "ヒント：”キーワード”は水族館の名称や説明文章などから検索します。"

    = render "common/lists"
  = render "top/side-bar"

= render "top/footer"

app/views/groups/show.html.haml
- flash.each do |message_type, message|
  .alert
    = message

= render "common/header"

.groups_show-main

  .aquarium
    .aquarium__head
      .aquarium__head--left
        %p
          = @group.catchphrase
        %h2
          = @group.name
        .aquarium__head--left--bottom
          %p.rate
            .rate-star{id: "star_rate_#{@group.id}"}

            :javascript
              $('#star_rate_#{@group.id}').raty({
                size: 36,
                starOff: "#{asset_path('star-off.png')}",
                starOn: "#{asset_path('star-on.png')}",
                starHalf: "#{asset_path('star-half.png')}",
                half: true,
                readOnly: true,
                score: "#{@group.comments.average(:rate).to_f.round(2)}",
              });

            %p.rate-number
              = @group.comments.average(:rate).to_f.round(2)
          .number
            %i.far.fa-comment-dots.icon
            %span
              = @group.comments.count
              件
            %i.far.fa-bookmark.icon
            %span
              = @group.likes.count
              件
      .aquarium__head--right
        .aquarium__head--right--top
          - if current_user.present?
            %div{id: "went-#{@group.id}", class: "went-btn"}
              = render "wents/went", group: @group
          - else
            = link_to new_user_session_path, class: "show-page_no-entry" do
              %i.far.fa-flag
              %span
                行った
        .aquarium__head--right--middle
          - if current_user.present?
            %div{id: "like-#{@group.id}", class: "like-btn"}
              = render "likes/like", group: @group
          - else
            = link_to new_user_session_path, class: "show-page_no-entry" do
              %i.far.fa-flag
              %span
                保存
        .aquarium__head--right--bottom
          - if current_user.present?
            #open
              %i.far.fa-comment-dots
              %span
                口コミする
          - else
            = link_to new_user_session_path, class: "show-page_no-entry" do
              %i.far.fa-comment-dots
              %span
                口コミする

    .aquarium__images-wrapper
      .aquarium__images-wrapper__main
        = image_tag @group.images[0].image.url, size: "600x450"
      .aquarium__images-wrapper__sub
        .aquarium__images-wrapper__sub--top
          = image_tag @group.images[1].image.url, size: "184x138"
        .aquarium__images-wrapper__sub--middle
          = image_tag @group.images[2].image.url, size: "184x138"
        .aquarium__images-wrapper__sub--bottom
          = image_tag @group.images[3].image.url, size: "184x138"

    .aquarium__explain
      %h3
        = @group.title
      %p
        = @group.text
        
    .aquarium-comments
      %h3 口コミ

      - unless @comments.present?
        .comment-none
          = " 口コミはまだありません"
      - else
        - @comments.each do |comment|
          .aquarium-comments__wrapper
            .aquarium-comments__wrapper__user
              .aquarium-comments__wrapper__user__image
                - if comment.user.image.url.present?
                  = image_tag comment.user.image.url, class: "comment-user-image"
                - else
                  = image_tag "member_photo_noimage_thumb.png", class: "comment-user-image"
              .aquarium-comments__wrapper__user__name
                = comment.user.name
            .aquarium-comments__wrapper__comment
              .aquarium-comments__wrapper__comment__title
                = comment.title
              .aquarium-comments__wrapper__comment__text
                = comment.text
              .aquarium-comments__wrapper__comment--bottom
                .aquarium-comments__wrapper__comment--bottom__rate
                  %p.rate
                    .rate-star{id: "star_rate_#{comment.id}"}

                    :javascript
                      $('#star_rate_#{comment.id}').raty({
                        size: 36,
                        starOff: "#{asset_path('star-off.png')}",
                        starOn: "#{asset_path('star-on.png')}",
                        starHalf: "#{asset_path('star-half.png')}",
                        score: #{comment.rate},
                        half: true,
                        readOnly: true,
                      });

                  %p.number
                    = comment.rate
                .aquarium-comments__wrapper__comment--bottom__time
                  行った時期：#{comment.visit_date}
                - if current_user.present?
                  - if comment.user.id == current_user.id
                    .aquarium-comments__wrapper__comment--bottom__edit
                      = link_to "編集", edit_group_comment_path(group_id: @group.id, id: comment.id)
                    .aquarium-comments__wrapper__comment--bottom__delete
                      = link_to "削除", group_comment_path(group_id: @group.id, id: comment.id), method: :delete

    #overlay
    #modal-window
      = render "comments/form"
    
  = render "top/side-bar"

= render "top/footer"

app/views/likes/_like.html.haml
- if Like.find_by(user_id: current_user.id, group_id: group.id)
  = link_to group_like_path(group_id: group.id, id: group.likes[0].id), method: :delete, remote: true do
    .like-btn__wrapper
      %i.fas.fa-bookmark
      %span
        保存

- else
  = link_to group_likes_path(group), method: :post, remote: true do
    .like-btn__wrapper
      %i.far.fa-bookmark
      %span
        保存
        

app/views/likes/create.js.haml
$("#like-#{@group.id}").html("#{j(render partial: 'like', locals: { group: @group })}");

app/views/likes/destroy.js.haml
$("#like-#{@group.id}").html("#{j(render partial: 'like', locals: { group: @group })}");

app/views/wents/_went.html.haml
- if Went.find_by(user_id: current_user.id, group_id: group.id)
  = link_to group_went_path(group_id: group.id, id: group.wents[0].id), method: :delete, remote: true do
    .went-btn__wrapper
      %i.fas.fa-flag
      %span
        行った

- else
  = link_to group_wents_path(group), method: :post, remote: true do
    .went-btn__wrapper
      %i.far.fa-flag
      %span
        行った

app/views/wents/create.js.haml
$("#went-#{@group.id}").html("#{j(render partial: 'went', locals: { group: @group })}");

app/views/wents/destroy.js.haml
$("#went-#{@group.id}").html("#{j(render partial: 'went', locals: { group: @group })}");